version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6370:6370"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    command: celery -A library_system worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A library_system beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1024:1024
      - 8024:8024

volumes:
  postgres_data:
